// Word pairs data for the impostor word game
// Each entry contains: secret word, hint, and category

export const WORD_PAIRS = [
  // Food (20 items)
  { secret: "Pizza", hint: "Food", category: "food" },
  { secret: "Pineapple", hint: "Fruit", category: "food" },
  { secret: "Sushi", hint: "Japanese dish", category: "food" },
  { secret: "Chocolate", hint: "Sweet treat", category: "food" },
  { secret: "Burger", hint: "Fast food", category: "food" },
  { secret: "Pasta", hint: "Italian dish", category: "food" },
  { secret: "Ice Cream", hint: "Frozen dessert", category: "food" },
  { secret: "Salad", hint: "Healthy dish", category: "food" },
  { secret: "Sandwich", hint: "Lunch item", category: "food" },
  { secret: "Soup", hint: "Hot liquid dish", category: "food" },
  { secret: "Taco", hint: "Mexican food", category: "food" },
  { secret: "Steak", hint: "Meat dish", category: "food" },
  { secret: "Rice", hint: "Grain", category: "food" },
  { secret: "Bread", hint: "Baked good", category: "food" },
  { secret: "Cheese", hint: "Dairy product", category: "food" },
  { secret: "Apple", hint: "Fruit", category: "food" },
  { secret: "Banana", hint: "Yellow fruit", category: "food" },
  { secret: "Cookie", hint: "Sweet snack", category: "food" },
  { secret: "Coffee", hint: "Hot beverage", category: "food" },
  { secret: "Cake", hint: "Dessert", category: "food" },

  // Location (20 items)
  { secret: "Canada", hint: "Country", category: "location" },
  { secret: "Volcano", hint: "Natural feature", category: "location" },
  { secret: "Paris", hint: "City", category: "location" },
  { secret: "Tokyo", hint: "Capital city", category: "location" },
  { secret: "Beach", hint: "Coastal area", category: "location" },
  { secret: "Mountain", hint: "Elevated landform", category: "location" },
  { secret: "Forest", hint: "Wooded area", category: "location" },
  { secret: "Desert", hint: "Arid region", category: "location" },
  { secret: "London", hint: "European city", category: "location" },
  { secret: "New York", hint: "US city", category: "location" },
  { secret: "Sydney", hint: "Australian city", category: "location" },
  { secret: "Egypt", hint: "African country", category: "location" },
  { secret: "Brazil", hint: "South American country", category: "location" },
  { secret: "Island", hint: "Land surrounded by water", category: "location" },
  { secret: "River", hint: "Flowing water", category: "location" },
  { secret: "Library", hint: "Building", category: "location" },
  { secret: "School", hint: "Educational place", category: "location" },
  { secret: "Hospital", hint: "Medical facility", category: "location" },
  { secret: "Airport", hint: "Transport hub", category: "location" },
  { secret: "Park", hint: "Public space", category: "location" },

  // Sports (20 items)
  { secret: "Basketball", hint: "Sport", category: "sports" },
  { secret: "Soccer", hint: "Team sport", category: "sports" },
  { secret: "Tennis", hint: "Racket sport", category: "sports" },
  { secret: "Swimming", hint: "Water sport", category: "sports" },
  { secret: "Football", hint: "American sport", category: "sports" },
  { secret: "Baseball", hint: "Bat and ball sport", category: "sports" },
  { secret: "Golf", hint: "Club sport", category: "sports" },
  { secret: "Volleyball", hint: "Net sport", category: "sports" },
  { secret: "Running", hint: "Track sport", category: "sports" },
  { secret: "Cycling", hint: "Bike sport", category: "sports" },
  { secret: "Boxing", hint: "Combat sport", category: "sports" },
  { secret: "Hockey", hint: "Ice sport", category: "sports" },
  { secret: "Skating", hint: "Ice activity", category: "sports" },
  { secret: "Surfing", hint: "Water sport", category: "sports" },
  { secret: "Skiing", hint: "Winter sport", category: "sports" },
  { secret: "Cricket", hint: "Bat and ball game", category: "sports" },
  { secret: "Rugby", hint: "Contact sport", category: "sports" },
  { secret: "Badminton", hint: "Racket sport", category: "sports" },
  { secret: "Archery", hint: "Target sport", category: "sports" },
  { secret: "Wrestling", hint: "Combat sport", category: "sports" },

  // Animals (20 items)
  { secret: "Elephant", hint: "Animal", category: "animals" },
  { secret: "Lion", hint: "Big cat", category: "animals" },
  { secret: "Dolphin", hint: "Marine mammal", category: "animals" },
  { secret: "Penguin", hint: "Bird", category: "animals" },
  { secret: "Tiger", hint: "Wild cat", category: "animals" },
  { secret: "Bear", hint: "Forest animal", category: "animals" },
  { secret: "Eagle", hint: "Bird of prey", category: "animals" },
  { secret: "Shark", hint: "Sea predator", category: "animals" },
  { secret: "Wolf", hint: "Pack animal", category: "animals" },
  { secret: "Giraffe", hint: "Tall animal", category: "animals" },
  { secret: "Monkey", hint: "Primate", category: "animals" },
  { secret: "Zebra", hint: "Striped animal", category: "animals" },
  { secret: "Kangaroo", hint: "Hopping animal", category: "animals" },
  { secret: "Panda", hint: "Black and white bear", category: "animals" },
  { secret: "Whale", hint: "Large marine mammal", category: "animals" },
  { secret: "Owl", hint: "Nocturnal bird", category: "animals" },
  { secret: "Snake", hint: "Reptile", category: "animals" },
  { secret: "Rabbit", hint: "Small mammal", category: "animals" },
  { secret: "Horse", hint: "Domesticated animal", category: "animals" },
  { secret: "Butterfly", hint: "Insect", category: "animals" },

  // Object (20 items)
  { secret: "Laptop", hint: "Electronics", category: "object" },
  { secret: "Twitter", hint: "App", category: "object" },
  { secret: "Tesla", hint: "Car", category: "object" },
  { secret: "Watch", hint: "Timepiece", category: "object" },
  { secret: "Camera", hint: "Photography device", category: "object" },
  { secret: "Phone", hint: "Communication device", category: "object" },
  { secret: "Book", hint: "Reading material", category: "object" },
  { secret: "Chair", hint: "Furniture", category: "object" },
  { secret: "Table", hint: "Furniture", category: "object" },
  { secret: "Lamp", hint: "Lighting", category: "object" },
  { secret: "Pen", hint: "Writing tool", category: "object" },
  { secret: "Bicycle", hint: "Vehicle", category: "object" },
  { secret: "Umbrella", hint: "Rain protection", category: "object" },
  { secret: "Glasses", hint: "Vision aid", category: "object" },
  { secret: "Shoes", hint: "Footwear", category: "object" },
  { secret: "Backpack", hint: "Carrying bag", category: "object" },
  { secret: "Mirror", hint: "Reflective surface", category: "object" },
  { secret: "Key", hint: "Lock opener", category: "object" },
  { secret: "Wallet", hint: "Money holder", category: "object" },
  { secret: "Headphones", hint: "Audio device", category: "object" },

  // Movies (keeping existing items)
  { secret: "Avatar", hint: "Movie", category: "movies" },
  { secret: "Titanic", hint: "Film", category: "movies" },
  { secret: "Inception", hint: "Sci-fi film", category: "movies" },
  { secret: "Frozen", hint: "Animated film", category: "movies" },
];
